/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _DATE_H_RPCGEN
#define _DATE_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


#define DATE_PROG ((rpc_uint)0x20000002)
#define DATE_VERS ((rpc_uint)1)

#ifdef __cplusplus
#define GET_DATE ((rpc_uint)1)
extern "C" long * get_date_1(void *, CLIENT *);
extern "C" long * get_date_1_svc(void *, struct svc_req *);

#elif __STDC__
#define GET_DATE ((rpc_uint)1)
extern  long * get_date_1(void *, CLIENT *);
extern  long * get_date_1_svc(void *, struct svc_req *);

#else /* Old Style C */
#define GET_DATE ((rpc_uint)1)
extern  long * get_date_1();
extern  long * get_date_1_svc();
#endif /* Old Style C */

#endif /* !_DATE_H_RPCGEN */
