/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _TRANS_H_RPCGEN
#define _TRANS_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>

#define MAXLENGTH 1024
#define MAXNAME 20

#define FILETRANSPROG ((rpc_uint)99)
#define FILETRANSVERS ((rpc_uint)1)

#ifdef __cplusplus
#define READFILE ((rpc_uint)1)
extern "C" char ** readfile_1(char **, CLIENT *);
extern "C" char ** readfile_1_svc(char **, struct svc_req *);

#elif __STDC__
#define READFILE ((rpc_uint)1)
extern  char ** readfile_1(char **, CLIENT *);
extern  char ** readfile_1_svc(char **, struct svc_req *);

#else /* Old Style C */
#define READFILE ((rpc_uint)1)
extern  char ** readfile_1();
extern  char ** readfile_1_svc();
#endif /* Old Style C */

#endif /* !_TRANS_H_RPCGEN */
